[mql mutation]update mql sever graphql schema for `updateMqlServerConfig`
transform-data/transform-react pull request #50
Opened 2021-10-03 18:39 UTC by conglei

# Changes
This is to update the graphql scheme per change in the PR https://github.com/transform-data/hedgehog/pull/1298

# Security Implications
No

2021-10-03 19:00 UTC, conglei commented
I don't know `UpdateMqlServerConfigMutationVariables` is not updated..

@jjrajani is there anything I did wrong?

```ts
export type UpdateMqlServerConfigMutationVariables = Exact<{
  mqlServerId: Scalars['Int'];
  dwPassword: Scalars['String'];
  tfdApiKey: Scalars['String'];
}>;
```

Thanks!

2021-10-04 14:33 UTC, jjrajani requested changes
The package version in `package.json` will also need to be updated.

2021-10-05 00:14 UTC, courtneyholcomb commented on schemas/core/core.graphql
> +  members(pageNumber: Int, pageSize: Int, orderBy: UserUserOrderBy, desc: Boolean): [TeamMember]
I think I may have introduced a but when generating the typename for this orderBy - it shouldn't have changed. (It gets generated in code, not hardcoded, hence me not catching this sooner)

2021-10-05 00:55 UTC, conglei commented
Just updated the schema again against production graphql endpoint. Still I'm very confused on why `UpdateMqlServerConfigMutationVariables` is not updated.. supposedly, the new added field `modeCreds` should be shown up there.

2021-10-05 21:38 UTC, jjrajani approved these changes

2021-10-05 21:40 UTC, merged